// <auto-generated/> DO NOT MANUALLY EDIT
#nullable enable
using Stocazzorm;

namespace Stocazzorm.IntegrationTests.Models;

[DataRecordMapper]
public partial class ByteOnlyModel
{
    public required byte Val { get; set; }
}
[DataRecordMapper]
public partial class ShortOnlyModel
{
    public required short Val { get; set; }
}
[DataRecordMapper]
public partial class IntOnlyModel
{
    public required int Val { get; set; }
}
[DataRecordMapper]
public partial class LongOnlyModel
{
    public required long Val { get; set; }
}
[DataRecordMapper]
public partial class FloatOnlyModel
{
    public required float Val { get; set; }
}
[DataRecordMapper]
public partial class DoubleOnlyModel
{
    public required double Val { get; set; }
}
[DataRecordMapper]
public partial class DecimalOnlyModel
{
    public required decimal Val { get; set; }
}
[DataRecordMapper]
public partial class StringOnlyModel
{
    public required string Val { get; set; }
}
[DataRecordMapper]
public partial class BoolOnlyModel
{
    public required bool Val { get; set; }
}
[DataRecordMapper]
public partial class GuidOnlyModel
{
    public required Guid Val { get; set; }
}
[DataRecordMapper]
public partial class CharOnlyModel
{
    public required char Val { get; set; }
}
[DataRecordMapper]
public partial class DateTimeOnlyModel
{
    public required DateTime Val { get; set; }
}
[DataRecordMapper]
public partial class NullableByteOnlyModel
{
    public byte? Val { get; set; }
}
[DataRecordMapper]
public partial class NullableShortOnlyModel
{
    public short? Val { get; set; }
}
[DataRecordMapper]
public partial class NullableIntOnlyModel
{
    public int? Val { get; set; }
}
[DataRecordMapper]
public partial class NullableLongOnlyModel
{
    public long? Val { get; set; }
}
[DataRecordMapper]
public partial class NullableFloatOnlyModel
{
    public float? Val { get; set; }
}
[DataRecordMapper]
public partial class NullableDoubleOnlyModel
{
    public double? Val { get; set; }
}
[DataRecordMapper]
public partial class NullableDecimalOnlyModel
{
    public decimal? Val { get; set; }
}
[DataRecordMapper]
public partial class NullableStringOnlyModel
{
    public string? Val { get; set; }
}
[DataRecordMapper]
public partial class NullableBoolOnlyModel
{
    public bool? Val { get; set; }
}
[DataRecordMapper]
public partial class NullableGuidOnlyModel
{
    public Guid? Val { get; set; }
}
[DataRecordMapper]
public partial class NullableCharOnlyModel
{
    public char? Val { get; set; }
}
[DataRecordMapper]
public partial class NullableDateTimeOnlyModel
{
    public DateTime? Val { get; set; }
}
