// <auto-generated/> DO NOT MANUALLY EDIT
using Nanorm;

namespace Nanorm.IntegrationTests.Utils;

public static class SqliteEnsureDb
{
    public const string CreateTables =
        """
        CREATE TABLE validate_byte(val INTEGER NOT NULL) STRICT;
        CREATE TABLE validate_short(val INTEGER NOT NULL) STRICT;
        CREATE TABLE validate_int(val INTEGER NOT NULL) STRICT;
        CREATE TABLE validate_long(val INTEGER NOT NULL) STRICT;
        CREATE TABLE validate_float(val REAL NOT NULL) STRICT;
        CREATE TABLE validate_double(val REAL NOT NULL) STRICT;
        CREATE TABLE validate_decimal(val TEXT NOT NULL) STRICT;
        CREATE TABLE validate_string(val TEXT NOT NULL) STRICT;
        CREATE TABLE validate_bool(val INTEGER NOT NULL) STRICT;
        CREATE TABLE validate_guid(val TEXT NOT NULL) STRICT;
        CREATE TABLE validate_char(val TEXT NOT NULL) STRICT;
        CREATE TABLE validate_datetime(val TEXT NOT NULL) STRICT;
        CREATE TABLE validate_nullable_byte(val INTEGER NULL) STRICT;
        CREATE TABLE validate_nullable_short(val INTEGER NULL) STRICT;
        CREATE TABLE validate_nullable_int(val INTEGER NULL) STRICT;
        CREATE TABLE validate_nullable_long(val INTEGER NULL) STRICT;
        CREATE TABLE validate_nullable_float(val REAL NULL) STRICT;
        CREATE TABLE validate_nullable_double(val REAL NULL) STRICT;
        CREATE TABLE validate_nullable_decimal(val TEXT NULL) STRICT;
        CREATE TABLE validate_nullable_string(val TEXT NULL) STRICT;
        CREATE TABLE validate_nullable_bool(val INTEGER NULL) STRICT;
        CREATE TABLE validate_nullable_guid(val TEXT NULL) STRICT;
        CREATE TABLE validate_nullable_char(val TEXT NULL) STRICT;
        CREATE TABLE validate_nullable_datetime(val TEXT NULL) STRICT;
        """;
}
